/*
 * Copyright 2025 Electronic Arts Inc.
 *
 * Derived from Electronic Arts Inc.'s public source release for
 * Command & Conquer: Red Alert.
 * Licensed under GPLv3-or-later with additional Electronic Arts terms.
 * Modified for the macOS port, 2026.
 * See LICENSE.md.
 */

#ifndef GAMEDLG_H
#define GAMEDLG_H

#include "gadget.h"

class GameControlsClass 
{
	public:
		GameControlsClass(void) {};
		void Process(void);
};


#endif

